---
abstract: 'POE-enabled OpenWeatherMap client'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Weather-OpenWeatherMap
requires:
  Defaults::Modern: 0
  Moo: 1
  MooX::Role::POE::Emitter: 0
  MooX::late: 0.014
  POE: 1
  POE::Component::Client::HTTP: 0
  Weather::OpenWeatherMap: 0.001005
  perl: v5.16.0
resources:
  repository: git://github.com/avenj/poex-weather-openweathermap.git
version: 0.001005
