---
abstract: 'POE-enabled OpenWeatherMap client'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Weather-OpenWeatherMap
requires:
  Carp: 0
  List::Objects::Types: 1
  Moo: 1
  MooX::late: 0.014
  POE: 1
  POE::Component::Client::HTTP: 0
  Types::Standard: 0
  Weather::OpenWeatherMap: 0.001002
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/poex-weather-openweathermap.git
version: 0.001001
